initial style markup
starodubbb/command-project-js pull request #2
Opened 2023-09-01 13:42 UTC by Mvic-net

2023-09-01 15:54 UTC, starodubbb approved these changes

2023-09-01 15:58 UTC, starodubbb requested changes
1. Два рази імпортується modern_normalize (у файлах _common.css та reset.css). Я би залишив тільки у _common.css.
2. Немає стилізації для контейнеру.
3. У стилізації секції немає бути горизонтальних падінгів (вони мають контролюватися контейнером).

2023-09-01 17:51 UTC, Mvic-net commented
> 1. Два рази імпортується modern_normalize (у файлах _common.css та reset.css). Я би залишив тільки у _common.css.
> 2. Немає стилізації для контейнеру.
> 3. У стилізації секції немає бути горизонтальних падінгів (вони мають контролюватися контейнером).

Поправил

2023-09-02 09:20 UTC, starodubbb approved these changes

2023-09-02 09:20 UTC, merged